name = "A"
uuid = "47d48b73-69d3-45cf-a35e-ec04f73e22fa"
authors = ["Cédric BELMANT"]
version = "0.1.1"

[weakdeps]
B = "0.1, 0.2"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
